### ISSUE TITLE
xyz.gff 、 xyz.html 等多个结果文件是空的

### ISSUE THREAD

**Issue by YanhuaRen** [sc-zhang/AlleleFinder#3]
老师，您好。我是利用AlleleFinder鉴定2倍体中的等位基因，有2个问题请教一下。
1. 我顺利运行完AlleleFinder -r  -d  -f  -c -g  -n -b -i  -e  -j  -w  -t  -m  code,没有产生任何报错。但是在01.mcscanx 文件中，xyz.gff 以及 xyz.html 文件是空的，后面的多个结果文件中也存在多个空文件。请问老师，这个问题应该如何解决？
2. 我运行结束后，在gmap以及blast文件中得出的结果仅是ref那一套基因组的基因，请老师帮忙解答。

**Comment by sc-zhang** [comment]
Please check makeblastdb, blastn, blastp in your PATH, then check xyz.blast empty or not. And the input gff3 file of polyploid must be chromosome level, and the id of chromosomes must not contain 'tig' or 'ctg'.

**Comment by YanhuaRen** [comment]
老师，你好。根据您的提示，已经将上述条件全部检查更改了，输出的结果中：xyz.blast 是有结果的，但是xyz.collinearity，xyz.gff，xyz.html 是没有结果。请如何解决？

**Comment by YanhuaRen** [comment]
老师，您好。我已经按照您的提示检查修改了上述问题。输出的结果中：xyz.blast 中有结果，但是xyz.collinearity，xyz.gff, xyz.html没有结果，请问这个如何解决？

**Comment by sc-zhang** [comment]
It may caused by the input gff3 file not contain any 'gene' line, please check the third column in the input gff3 file.

**Comment by YanhuaRen** [comment]
谢谢老师，问题已解决。请问老师能否提供下结果文件的说明？

**Comment by YanhuaRen** [comment]
老师，你好。我们进行了一个果树二倍体的单倍型测序，要进行等位基因分析。我们运行脚本：AlleleFinder -r hap1.genome.fa -d hap1.cds.fa -f hap1.gff -c PN_hap2.cds.fa -g hap2.gff -n 2 -b 2 -e NULL -i 80 -w WDIR1 -m --is_mono。其中：hap1为ref genome，hap2为polyploid genome (hap1+hap2,两套单独注释的单倍型和在一起)。cds和gff文件都为对应的两种类型（hap1或者hap1+2）输出结果文件为：01.mcscanx, 02.gmap, 03.blast, 04.ref_adjust, allele.csv, backbone.csv。请问这样的文件是否符合要求？
同时，运行时出现了以下几个问题：
1、运行最终结果 ‘Step6: Adjusting with ref annotation’未输出结果文件‘allele.adjusted.txt’。
2、单独运行‘Step6: python AlleleFinder/bin/adjust_allele_table_with_ref.py allele.csv hap1.gff hap2.gff WDIR1/04.ref_adjust/hap2.vs.hap1.blast WDIR1/01.mcscanx/xyz/xyz.blast 80.000000 WDIR1/01.mcscanx/xyz/xyz.tandem 2 allele.adjusted.txt T’ 。
出现报错：
Traceback (most recent call last):
  File "AlleleFinder/bin/adjust_allele_table_with_ref.py", line 158, in <module>
    adjust_allele_table(in_allele, ref_gff3, hap_gff3, ref_blast, hap_blast, float(iden), tandem, int(allele_num), out_allele, is_mono)
  File "AlleleFinder/bin/adjust_allele_table_with_ref.py", line 102, in adjust_allele_table
    info_db[ref_gn][hidx].append([hpos, id])
IndexError: list index out of range
3、我们比对‘Step1: running MCScanX’输出文件中xyz.collinearity 的 Percentage: 6.01。单独运行MCScanX的输出文件中xyz.collinearity 的 Percentage: 70.11。
4、结果文件01.mcscanx xyz xyz.html Collinear blocks处为空白，未比对上任何信息。

**Comment by sc-zhang** [comment]
For question 1 and 2, please check the chromosome name in polyploid is like Chr1A, the last character should be A to Z (A means 1, B means 2...).
For question 3 and 4, please run MCScanX with the xyz.blast and xyz.gff generate by run_MCScanX.py and check if the result is same or not.

**Comment by YanhuaRen** [comment]
感谢老师答疑，我们根据您的方法修改了文件格式，成功运行脚本，结果文件中发现几个问题请教老师， 

1、结果文件01.mcscanx/xyz 文件夹中 xyz.html结果中 Collinear blocks 多数为0 ；xyz.collinearity的 Percentage: 为5.44，与我们使用其他软件得出的结果（70.11）有较大差异。此外，我查看结果文件 ‘allele.adjusted.txt' 中两个单倍型的基因有80%左右匹配为了等位基因对。请问这是什么原因？

2、输出的结果文件中未找到‘allele.adjusted.*.stat’等位基因的统计信息

**Comment by YanhuaRen** [comment]
运行后结果文件中发现几个问题请老师解答：

1、结果文件01.mcscanx/xyz 文件夹中 xyz.html结果中 Collinear blocks 绝多数为0，并且Reference chromosome 列 单倍型A和B的基因交替顺次排列， Collinear blocks列 无信息。所有染色体输出结果均出现同样问题。结果如展示下：
Duplication depth	  Reference chromosome	  Collinear blocks
0	Chr01BG00001.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00002.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00001.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00002.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00003.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00003.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00004.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00005.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00004.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00005.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00006.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00006.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00007.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01AG00007.1	 	 	 	 	 	 	 	 	 	 	 
0	Chr01BG00008.1	 	 	 	 	 	 	 	 	 	 	 

2、xyz.collinearity的 Percentage: 为5.44，而结果文件 ‘allele.adjusted.txt' 中两个单倍型的基因有80%左右匹配为了等位基因对。请问这个是什么原因？xyz.collinearity 结果文件如下：
############### Parameters ###############
# MATCH_SCORE: 50
# MATCH_SIZE: 5
# GAP_PENALTY: -1
# OVERLAP_WINDOW: 5
# E_VALUE: 1e-05
# MAX GAPS: 25
############### Statistics ###############
# Number of collinear genes: 3330, Percentage: 5.44
# Number of all genes: 61212
##########################################
## Alignment 0: score=296.0 e_value=4.6e-08 N=6 NN01&NN01 plus
  0-  0:	Chr01AG01656.1	Chr01BG01628.1	      0
  0-  1:	Chr01AG01657.1	Chr01BG01629.1	      0
  0-  2:	Chr01AG01658.1	Chr01BG01630.1	      0
  0-  3:	Chr01AG01659.1	Chr01BG01631.1	      0
  0-  4:	Chr01AG01660.1	Chr01BG01632.1	      0
  0-  5:	Chr01AG01661.1	Chr01BG01633.1	      0
## Alignment 1: score=291.0 e_value=2.7e-15 N=6 NN01&NN01 minus
  1-  0:	Chr01AG01227.1	Chr01BG01240.1	 2e-146
  1-  1:	Chr01AG01228.1	Chr01BG01238.1	      0
  1-  2:	Chr01AG01229.1	Chr01BG01237.1	      0
  1-  3:	Chr01AG01230.1	Chr01BG01234.1	      0
  1-  4:	Chr01AG01231.1	Chr01BG01233.1	      0
  1-  5:	Chr01AG01232.1	Chr01BG01232.1	  6e-43

3、‘allele.adjusted.*.stat’等位基因的统计信息 这个结果未输出。
